#!/usr/bin/env bash
# 초기 시드 및 재배포 스크립트:
#   1. soldesk-app 현재 git HEAD SHA 로 이미지 태깅하여 ECR 에 push
#   2. ArgoCD Application 의 image tag parameter 를 이 SHA 로 patch
#      → ArgoCD 가 auto-sync 하여 pod 재생성 (새 이미지 pull)
#   3. frontend/src 를 S3 에 sync + CloudFront invalidation
#
# 사전 요구: docker, aws CLI, kubectl (ArgoCD 에 접속 가능한 kubeconfig).
# 사용법: bash scripts/seed.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INFRA_TF="${INFRA_TF:-$ROOT/../soldesk-infra/terraform}"

[ -d "$INFRA_TF" ] || { echo "ERROR: $INFRA_TF 없음. INFRA_TF=<path> 로 지정." >&2; exit 1; }

tf_out() { terraform -chdir="$INFRA_TF" output -raw "$1" 2>/dev/null; }

REGION="$(tf_out aws_region)"
ACCOUNT_ID="$(tf_out aws_account_id)"
ECR_REGISTRY="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"
BUCKET="$(tf_out frontend_bucket)"
CF_DIST_ID="$(tf_out cloudfront_distribution_id)"
API_ENDPOINT="$(tf_out api_gateway_endpoint)"
COGNITO_USER_POOL_ID="$(tf_out cognito_user_pool_id)"
COGNITO_CLIENT_ID="$(tf_out cognito_client_id)"

for v in REGION ACCOUNT_ID BUCKET CF_DIST_ID API_ENDPOINT COGNITO_USER_POOL_ID COGNITO_CLIENT_ID; do
  [ -z "${!v}" ] && { echo "ERROR: terraform output $v 비어있음"; exit 1; }
done

# soldesk-app git SHA → 이미지 태그 (짧은 12자리)
IMAGE_TAG="$(git -C "$ROOT" rev-parse --short=12 HEAD 2>/dev/null || echo "")"
[ -z "$IMAGE_TAG" ] && { echo "ERROR: soldesk-app 이 git repo 가 아님 — IMAGE_TAG 결정 불가"; exit 1; }

echo "==> 시드 설정"
echo "  ECR tag : $IMAGE_TAG"
echo "  ECR     : $ECR_REGISTRY"
echo "  S3      : $BUCKET"
echo "  API     : $API_ENDPOINT"

# ── 0. DB 스키마 초기화 (최초 1회) ───────────────────────────────
# "Table ticketing.* doesn't exist" 방지. 이미 있으면 --force 로 무시.
echo "==> [0/4] DB 스키마 초기화"
DB_WRITER_HOST="$(terraform -chdir="$INFRA_TF" output -raw rds_writer_endpoint 2>/dev/null || true)"
if [ -z "${DB_PASSWORD:-}" ]; then
  DB_PASSWORD="$(grep '^db_password' "$INFRA_TF/terraform.tfvars" 2>/dev/null | sed 's/.*= *"//;s/".*//' || true)"
fi

if [ -z "$DB_WRITER_HOST" ] || [ -z "$DB_PASSWORD" ]; then
  echo "  WARN: RDS writer 또는 DB_PASSWORD 를 얻을 수 없음 — DB 스키마 초기화 건너뜀"
else
  kubectl -n ticketing delete pod mysql-init --ignore-not-found --wait=true >/dev/null 2>&1 || true
  kubectl -n ticketing run mysql-init --image=mysql:8.0 --restart=Never \
    --command -- sleep 3600 >/dev/null
  echo "  mysql-init pod 대기..."
  kubectl -n ticketing wait --for=condition=Ready pod/mysql-init --timeout=120s >/dev/null

  echo "  create.sql 실행 (기존 테이블 있으면 무시)"
  kubectl -n ticketing exec -i mysql-init -- \
    mysql --force --default-character-set=utf8mb4 \
    -h "$DB_WRITER_HOST" -u root -p"$DB_PASSWORD" \
    < "$ROOT/db-schema/create.sql" 2>&1 | tail -5 || true

  echo "  Insert.sql (시드 데이터)"
  kubectl -n ticketing exec -i mysql-init -- \
    mysql --force --default-character-set=utf8mb4 \
    -h "$DB_WRITER_HOST" -u root -p"$DB_PASSWORD" ticketing \
    < "$ROOT/db-schema/Insert.sql" 2>&1 | tail -5 || true

  kubectl -n ticketing delete pod mysql-init --wait=false --ignore-not-found >/dev/null
  echo "  DB 스키마 초기화 완료"
fi

# ── 1. ECR push ────────────────────────────────────────────────────
echo "==> [1/4] ECR 로그인 + 빌드 + push"
aws ecr get-login-password --region "$REGION" \
  | docker login --username AWS --password-stdin "$ECR_REGISTRY"

for SVC in ticketing-was worker-svc; do
  IMG="${ECR_REGISTRY}/ticketing/${SVC}:${IMAGE_TAG}"
  echo "  빌드: $SVC → $IMG"
  docker build -t "$IMG" "$ROOT/services/$SVC"
  docker push "$IMG"
done

# ── 2. ArgoCD Application image tag patch ─────────────────────────
echo "==> [2/4] ArgoCD Application image tag patch → $IMAGE_TAG"
if kubectl -n argocd get application ticketing-prod >/dev/null 2>&1; then
  # helm.parameters 를 JSON Patch 로 찾아 교체.
  # images.was.tag / images.worker.tag 둘 다 업데이트.
  PARAMS_JSON="$(kubectl -n argocd get application ticketing-prod \
    -o jsonpath='{.spec.source.helm.parameters}')"
  NEW_PARAMS="$(echo "$PARAMS_JSON" | python3 -c '
import sys, json
params = json.load(sys.stdin)
tag = "'"$IMAGE_TAG"'"
for p in params:
    if p["name"] in ("images.was.tag", "images.worker.tag"):
        p["value"] = tag
print(json.dumps(params))
')"

  kubectl -n argocd patch application ticketing-prod --type merge \
    -p "{\"spec\":{\"source\":{\"helm\":{\"parameters\":$NEW_PARAMS}}}}"

  # ArgoCD 가 다음 polling(3분) 기다리지 않도록 즉시 sync 유도
  kubectl -n argocd annotate application ticketing-prod \
    argocd.argoproj.io/refresh=hard --overwrite >/dev/null
  echo "  Application patched. ArgoCD 가 새 SHA 로 재동기화합니다."
else
  echo "  WARN: ticketing-prod Application 이 없습니다."
  echo "  먼저 soldesk-infra 에서 apply.sh 를 실행하세요."
fi

# ── 3. 프론트엔드 S3 sync + CloudFront invalidation ──────────────
echo "==> [3/4] 프론트엔드 S3 배포"
TMP_FRONT="$(mktemp -d)"
cp -r "$ROOT/frontend/src/." "$TMP_FRONT/"
cat > "$TMP_FRONT/api-origin.js" <<EOF
// generated by scripts/seed.sh — do not hand-edit
window.__TICKETING_API_ORIGIN__ = "${API_ENDPOINT}";
window.COGNITO_CONFIG = {
  REGION: "${REGION}",
  USER_POOL_ID: "${COGNITO_USER_POOL_ID}",
  CLIENT_ID: "${COGNITO_CLIENT_ID}"
};
EOF

aws s3 sync "$TMP_FRONT/" "s3://${BUCKET}/" --region "$REGION" --delete \
  --cache-control "public, max-age=300"
rm -rf "$TMP_FRONT"

aws cloudfront create-invalidation \
  --distribution-id "$CF_DIST_ID" --paths "/*" >/dev/null
echo "  CloudFront 무효화 생성 (전파 3~5분)"

echo ""
echo "==> 시드 완료 (tag=$IMAGE_TAG)"
echo "  프론트엔드: https://$(tf_out cloudfront_domain)"
echo "  pod 상태  : kubectl -n ticketing get pods -w"
